# Generated by Django 5.0.6 on 2024-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0002_alter_mortgage_user_remove_mortgage_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='paid_interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='paid_principal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
