# Generated by Django 5.0.6 on 2024-05-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0004_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='date',
            new_name='pub_date',
        ),
    ]
