# Generated by Django 5.0.6 on 2024-05-17 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0005_rename_date_blogpost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
