# Generated by Django 5.0.6 on 2024-05-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0006_alter_mortgage_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pub_date']},
        ),
    ]
