# Generated by Django 4.2.13 on 2024-05-27 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0010_alter_loan_loan_type_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 16, 48, 20, 355515, tzinfo=datetime.timezone.utc)),
        ),
    ]
