# Generated by Django 4.2.13 on 2024-05-27 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0012_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 17, 2, 53, 739275, tzinfo=datetime.timezone.utc)),
        ),
    ]
