# Generated by Django 4.2.13 on 2024-05-28 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mortgage', '0013_subscription_amount_alter_subscription_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAdhoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('FOD', 'Food'), ('CLT', 'Clothing'), ('PSL', 'Personal'), ('ENT', 'Entertainment'), ('EDU', 'Education'), ('CHD', 'Childcare'), ('GFT', 'Gifts'), ('INS', 'Insurance'), ('HOS', 'Housing'), ('UTI', 'Utilities'), ('HLT', 'Health'), ('TRS', 'Transport'), ('VEH', 'Vehicle'), ('TAX', 'Taxes'), ('ECY', 'Emergency'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=10.0)),
                ('category', models.CharField(choices=[('HOS', 'Housing'), ('UTI', 'Utilities'), ('INS', 'Insurance'), ('EDU', 'Education'), ('CHD', 'Childcare'), ('HLT', 'Health'), ('TRS', 'Transport'), ('VEH', 'Vehicle'), ('TAX', 'Taxes'), ('SUB', 'Subscription'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('interval', models.CharField(choices=[('WK', 'Weekly'), ('FT', 'Fortnightly'), ('MT', 'Monthly'), ('QT', 'Quarterly'), ('AN', 'Annual'), ('OT', 'Other')], default='OTH', max_length=2)),
                ('payments_per_year', models.IntegerField(default=12)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
