# Generated by Django 4.2.13 on 2024-05-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0014_expenseadhoc_expenseinterval_delete_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseinterval',
            old_name='start_date',
            new_name='next_payment_date',
        ),
    ]
