# Generated by Django 4.2.13 on 2024-05-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0016_expenseadhoc_approved_expenseadhoc_expenseinterval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='description',
            field=models.CharField(default='description', max_length=50),
        ),
    ]
