# Generated by Django 4.2.13 on 2024-05-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0017_loan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinterval',
            name='interval',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
    ]
