# Generated by Django 4.2.13 on 2024-05-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0018_alter_expenseinterval_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseadhoc',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Personal', 'Personal'), ('Entertainment', 'Entertainment'), ('Subscription', 'Subscription'), ('Transport', 'Transport'), ('Education', 'Education'), ('Health', 'Health'), ('Childcare', 'Childcare'), ('Gift', 'Gift'), ('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Vehicle', 'Vehicle'), ('Taxes', 'Taxes'), ('Emergency', 'Emergency'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='expenseinterval',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Personal', 'Personal'), ('Entertainment', 'Entertainment'), ('Subscription', 'Subscription'), ('Transport', 'Transport'), ('Education', 'Education'), ('Health', 'Health'), ('Childcare', 'Childcare'), ('Gift', 'Gift'), ('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Vehicle', 'Vehicle'), ('Taxes', 'Taxes'), ('Emergency', 'Emergency'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
