# Generated by Django 4.2.13 on 2024-05-30 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0019_alter_expenseadhoc_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseinterval',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mortgage.loan'),
        ),
    ]
