# Generated by Django 4.2.13 on 2024-05-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0020_expenseinterval_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount',
            new_name='amount_initial',
        ),
        migrations.RemoveField(
            model_name='expenseadhoc',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='deposit',
        ),
        migrations.AddField(
            model_name='expenseadhoc',
            name='loan_amount_interest',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='expenseadhoc',
            name='loan_amount_principal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='loan',
            name='amount_remaining',
            field=models.FloatField(default=180000),
        ),
    ]
