# Generated by Django 4.2.13 on 2024-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0021_rename_amount_loan_amount_initial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseadhoc',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
