# Generated by Django 4.2.13 on 2024-05-30 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0022_expenseadhoc_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseadhoc',
            name='amount',
        ),
        migrations.AddField(
            model_name='expenseinterval',
            name='last_payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
