# Generated by Django 4.2.13 on 2024-05-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0023_remove_expenseadhoc_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseadhoc',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
