# Generated by Django 4.2.13 on 2024-05-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0024_expenseadhoc_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='amount_remaining',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='paid_interest',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='paid_principal',
        ),
        migrations.AddField(
            model_name='loan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expenseinterval',
            name='interval',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annual', 'Annual')], default='Monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_initial',
            field=models.FloatField(default=10000),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('Mortgage', 'Mortgage'), ('Home Equity', 'Home Equity'), ('Car', 'Car'), ('Personal', 'Personal'), ('Student', 'Student'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
