# Generated by Django 4.2.13 on 2024-05-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0025_remove_loan_amount_remaining_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount_initial',
            new_name='amount',
        ),
    ]
