# Generated by Django 4.2.13 on 2024-06-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0026_rename_amount_initial_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseadhoc',
            name='loan_amount_interest',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='expenseadhoc',
            name='loan_amount_principal',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
