# Generated by Django 4.2.13 on 2024-06-12 15:10

import backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(default='username', max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', backend.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='description', max_length=50)),
                ('amount', models.FloatField(default=10000)),
                ('interest_rate', models.FloatField(default=5.0)),
                ('loan_type', models.CharField(choices=[('Mortgage', 'Mortgage'), ('Home Equity', 'Home Equity'), ('Car', 'Car'), ('Personal', 'Personal'), ('Student', 'Student'), ('Other', 'Other')], default='Other', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=10.0)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Personal', 'Personal'), ('Entertainment', 'Entertainment'), ('Subscription', 'Subscription'), ('Transport', 'Transport'), ('Education', 'Education'), ('Health', 'Health'), ('Childcare', 'Childcare'), ('Gift', 'Gift'), ('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Vehicle', 'Vehicle'), ('Taxes', 'Taxes'), ('Emergency', 'Emergency'), ('Other', 'Other')], default='Other', max_length=20)),
                ('interval', models.CharField(choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annual', 'Annual')], default='Monthly', max_length=20)),
                ('payments_per_year', models.IntegerField(default=12)),
                ('next_payment_date', models.DateField(default=django.utils.timezone.now)),
                ('last_payment_date', models.DateField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseAdhoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Personal', 'Personal'), ('Entertainment', 'Entertainment'), ('Subscription', 'Subscription'), ('Transport', 'Transport'), ('Education', 'Education'), ('Health', 'Health'), ('Childcare', 'Childcare'), ('Gift', 'Gift'), ('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Vehicle', 'Vehicle'), ('Taxes', 'Taxes'), ('Emergency', 'Emergency'), ('Other', 'Other')], default='Other', max_length=20)),
                ('approved', models.BooleanField(default=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('loan_amount_principal', models.FloatField(blank=True, default=0.0, null=True)),
                ('loan_amount_interest', models.FloatField(blank=True, default=0.0, null=True)),
                ('expenseinterval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.expenseinterval')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
