# Generated by Django 4.2.13 on 2024-06-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseAdhoc',
            new_name='Expense',
        ),
        migrations.RenameModel(
            old_name='ExpenseInterval',
            new_name='RegularPayment',
        ),
    ]
