# Generated by Django 4.2.13 on 2024-06-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_expenseadhoc_expense_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expenseinterval',
            new_name='regularpayment',
        ),
    ]
