# Generated by Django 4.2.13 on 2024-06-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_expenseinterval_expense_regularpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
