# Generated by Django 4.2.13 on 2024-07-19 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_email_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularpayment',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='regularpayment',
            name='payments_per_year',
        ),
        migrations.AddField(
            model_name='regularpayment',
            name='first_payment_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 19, 9, 21, 29, 824402, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='regularpayment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regularpayment',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Personal', 'Personal'), ('Entertainment', 'Entertainment'), ('Subscription', 'Subscription'), ('Transport', 'Transport'), ('Education', 'Education'), ('Health', 'Health'), ('Childcare', 'Childcare'), ('Gift', 'Gift'), ('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Vehicle', 'Vehicle'), ('Taxes', 'Taxes'), ('Emergency', 'Emergency'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='regularpayment',
            name='interval',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annual', 'Annual')], max_length=20),
        ),
        migrations.AlterField(
            model_name='regularpayment',
            name='next_payment_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 19, 9, 21, 29, 824402, tzinfo=datetime.timezone.utc)),
        ),
    ]
