# Generated by Django 4.2.13 on 2024-07-19 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_regularpayment_last_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpayment',
            name='first_payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='regularpayment',
            name='next_payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
