# Generated by Django 4.2.13 on 2024-08-02 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_regularpayment_first_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('Wages', 'Wages'), ('Sale', 'Sale'), ('Other', 'Other')], max_length=20)),
                ('interval', models.CharField(choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Annual', 'Annual')], max_length=20)),
                ('next_payment_date', models.DateField(default=django.utils.timezone.now)),
                ('first_payment_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('category', models.CharField(choices=[('Wages', 'Wages'), ('Sale', 'Sale'), ('Other', 'Other')], default='Other', max_length=20)),
                ('approved', models.BooleanField(default=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('regularincome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.regularincome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
